#!/usr/bin/env bash

BLANK='#313244'
CLEAR='#313244'
DEFAULT='#313244'
TEXT='#a6e3a1'
WRONG='#f38ba8'
VERIFYING='#a6e3a1'

i3lock \
--insidever-color=$CLEAR \
--ringver-color=$VERIFYING \
--insidewrong-color=$CLEAR \
--ringwrong-color=$WRONG \
--inside-color=$BLANK \
--ring-color=$DEFAULT \
--line-color=$BLANK \
--separator-color=$DEFAULT \
--verif-color=$TEXT \
--wrong-color=$TEXT \
--time-color=$TEXT \
--date-color=$TEXT \
--layout-color=$TEXT \
--keyhl-color=$WRONG \
--bshl-color=$WRONG \
--screen 1 \
--blur 4 \
--clock \
--indicator \
--time-str="%H:%M:%S" \
--date-str="%A, %Y-%m-%d" \
--keylayout 1
